# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraftVersion=1.21.1
yarnMappings=1.21.1+build.3
loaderVersion=0.16.3
fabricKotlinVersion=1.11.0+kotlin.2.0.0
# Mod Properties
modVersion=1.0.0
mavenGroup=heckerpowered.matrix
archiveBaseName=matrix
# Dependencies
fabricVersion=0.103.0+1.21.1