#
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 heckerpowered
#
org.gradle.jvmargs=-Xms1g -Xmx4g -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
# org.gradle.configuration-cache=true
org.gradle.vfs.watch=true
org.gradle.daemon.idletimeout=900000
# General Properties
minecraftVersion=1.21
kotlinVersion=2.2.0
# Fabric Properties
# check these on https://fabricmc.net/develop
yarnMappings=1.21+build.9
loaderVersion=0.17.2
fabricKotlinVersion=1.13.4+kotlin.2.2.0
fabricVersion=0.102.0+1.21
loomVersion=1.11-SNAPSHOT
# Mod Properties
modVersion=1.0.0
mavenGroup=heckerpowered.matrix
archiveBaseName=matrix