package heckerpowered.matrix.client.render.particle.module

enum class ParticleStateElement {
    POSITION_X, POSITION_Y, POSITION_Z,
    VELOCITY_X, VELOCITY_Y, VELOCITY_Z,
    ACCELERATION_X, ACCELERATION_Y, ACCELERATION_Z,
    SPRITE_SIZE, SCALE,
    AGE, LIFETIME,
    COLOR_R, COLOR_G, COLOR_B, COLOR_A,
    ORIENTATION_X, ORIENTATION_Y, ORIENTATION_Z, ORIENTATION_W,
    ANGULAR_VELOCITY_X, ANGULAR_VELOCITY_Y, ANGULAR_VELOCITY_Z,
}